// Run against an isolated fixture server, never the production database.
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');

(async () => {
  const browser = await chromium.launch({channel: 'msedge', headless: true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    const base=process.env.IFA_TEST_URL || 'http://127.0.0.1:5097';
    const output=process.env.IFA_TEST_OUTPUT || path.join(__dirname,'../../../..','tmp/ifa-review');
    fs.mkdirSync(output,{recursive:true});
    await page.goto(base+'/ifa');
    await page.locator('[name=username]').fill('admin');
    assert.ok(process.env.IFA_TEST_PASSWORD, 'Defina IFA_TEST_PASSWORD para o banco fictício');
    await page.locator('[name=password]').fill(process.env.IFA_TEST_PASSWORD);
    await page.locator('button[type=submit]').click();
    await page.waitForURL('**/ifa/principal');
    await page.goto(base+'/ifa/avaliacoes/nova');
    await page.locator('#agentSelect').selectOption('1');
    await page.locator('#competenceSelect').selectOption('2026-01');
    const card=order=>page.locator(`.indicator-card[data-category=ACS][data-order-index="${order}"]`);
    const pair=async(order,n,d)=>{await card(order).locator('.numerator').fill(n);await card(order).locator('.denominator').fill(d)};
    assert.equal(await card(2).locator('.numerator').isDisabled(),true);
    assert.equal(await card(4).locator('.numerator').getAttribute('required'),null);
    await pair(1,'80','100');
    assert.equal(await page.locator('#liveTotal').innerText(),'100.00');
    assert.equal(await page.locator('#evaluationForm').evaluate(el=>el.checkValidity()),true);
    await pair(1,'','100');
    assert.equal(await page.locator('#liveTotal').innerText(),'—');
    assert.equal(await page.locator('#evaluationForm').evaluate(el=>el.checkValidity()),false);
    await pair(1,'0','100');
    assert.equal(await page.locator('#liveTotal').innerText(),'50.00');
    await pair(1,'40','100');
    await page.locator('[name=proportional_factor]').fill('50');
    assert.equal(await page.locator('#liveTotal').innerText(),'100.00');
    await page.locator('[name=proportional_factor]').fill('100');
    await page.locator('#competenceSelect').selectOption('2026-12');
    assert.equal(await card(2).locator('.numerator').isDisabled(),false);
    await pair(1,'80','100');
    await pair(2,'0','100');
    assert.equal(await page.locator('#liveTotal').innerText(),'75.00');
    await page.screenshot({path:path.join(output,'formulario-desktop.png'),fullPage:true,animations:'disabled'});
    await page.locator('button[type=submit]').click();
    await page.waitForURL('**/ifa/avaliacoes/detalhe/*');
    const id=page.url().split('/').at(-1);
    await page.goto(base+'/ifa/relatorios?agente=1&ano=2026&salario=3000');
    assert.match(await page.locator('.payment-summary').innerText(),/75.00%/);
    assert.match(await page.locator('.payment-summary').innerText(),/2250.00/);
    await page.goto(base+'/ifa/avaliacoes/editar/'+id);
    await pair(2,'','');
    assert.equal(await page.locator('#liveTotal').innerText(),'100.00');
    await page.locator('button[type=submit]').click();
    await page.waitForURL('**/ifa/avaliacoes/detalhe/*');
    await page.goto(base+'/ifa/relatorios?agente=1&ano=2026&salario=3000');
    assert.match(await page.locator('.payment-summary').innerText(),/100.00%/);
    await page.screenshot({path:path.join(output,'relatorio-desktop.png'),fullPage:true,animations:'disabled'});
    await page.setViewportSize({width:390,height:844});
    await page.screenshot({path:path.join(output,'relatorio-mobile.png'),fullPage:true,animations:'disabled'});
    await page.goto(base+'/ifa/avaliacoes/nova');
    await page.locator('#agentSelect').selectOption('1');
    assert.equal(await page.locator('#competenceSelect option[value="2026-12"]').evaluate(el=>el.disabled),true,JSON.stringify(await page.evaluate(()=>window.EXISTING_COMPETENCES)));
    await page.locator('#competenceSelect').selectOption('2026-02');
    await page.locator('[name=leave_type][value=ferias]').check();
    assert.equal(await card(1).locator('.numerator').isDisabled(),true);
    assert.equal(await page.locator('#liveTotal').innerText(),'—');
    await page.locator('[name=leave_justification]').fill('Férias oficiais');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(output,'formulario-mobile.png'),fullPage:true,animations:'disabled'});
    await page.locator('button[type=submit]').click();
    await page.waitForURL('**/ifa/avaliacoes/detalhe/*');
    assert.match(await page.locator('body').innerText(),/Nenhum indicador computado/);
    assert.deepEqual(errors,[]);
    console.log('PASS: navegador — branco, zero, par incompleto, fator, regras anuais, salvar, editar, relatório, duplicação, férias e responsividade.');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1});
